name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: npm test # Replace this with your test command


      # - name: Deploy if tests pass
      #   i f: succes s()
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${ { secrets.SERVER_HOST }}
      #     username: $ {{ secrets.SERVER_USERNAME }}
      #     password: ${ { secrets.SERVER_PASSWORD }}
      #     script: |
      #       # Run commands on the server after successful tests
      #       echo "Commands to run on the server"
      #       # Example: ssh user@host "command1 && command2"
